{
 "title": "Kafka Basic metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Kafka Bytes in",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_bytesinpersec_count"
    }
   ]
  },
  {
   "title": "Kafka bytes out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_bytesoutpersec_count"
    }
   ]
  },
  {
   "title": "Kafka under replicated partiotions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kafka_topic_partition_under_replicated_partition"
    }
   ]
  },
  {
   "title": "Kafka current offset by topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset"
    }
   ]
  }
 ]
}